CREATE TABLE #SKJEMA#.PS_PERSON_01
( PS01_PERSONKEY NUMBER(15, 0) NOT NULL
    , PS01_NSB CHAR(1 CHAR) NOT NULL
    , PS01_TILGANGS_MND NUMBER(6, 0) NOT NULL
    , PS01_PENS_DODSMND NUMBER(7, 0) NOT NULL
    , PS01_OPPHORS_KODE CHAR(1 CHAR) NOT NULL
    , PS01_SIST_UTB_MND NUMBER(6, 0) NOT NULL
    , PS01_KORTNR_LAV NUMBER(7, 0) NOT NULL
    , PS01_KORT_ANT CHAR(1 CHAR) NOT NULL
    , PS01_OPPHOR_MND NUMBER(6, 0) NOT NULL
    , PS01_PM_MASK CHAR(2 CHAR) NOT NULL
    , PS01_PM1 CHAR(2 CHAR) NOT NULL
    , PS01_PM2 CHAR(2 CHAR) NOT NULL
    , PS01_TRYGDETID NUMBER(2, 0) NOT NULL
    , PS01_ETTERBET NUMBER(6, 0) NOT NULL
    , PS01_TRYGDETID_E NUMBER(2, 0) NOT NULL
    , TK_NR VARCHAR2(4 BYTE) NOT NULL
    , F_NR VARCHAR2(11 BYTE) NOT NULL
    , OPPRETTET TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    , ENDRET_I_KILDE TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    , KILDE_IS VARCHAR2(12 CHAR) DEFAULT ' ' NOT NULL
    , REGION CHAR(1 CHAR) DEFAULT ' ' NOT NULL
    , ID_PS_PERS NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 200 NOT NULL
    , OPPDATERT TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    )
;

CREATE TABLE #SKJEMA#.PS_KONTO_10
( PS01_PERSONKEY NUMBER(15, 0) NOT NULL
    , PS10_KONTONR NUMBER(4, 0) NOT NULL
    , PS10_BEH_KODE CHAR(1 CHAR) NOT NULL
    , TK_NR VARCHAR2(4 BYTE) NOT NULL
    , F_NR VARCHAR2(11 BYTE) NOT NULL
    , OPPRETTET TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    , ENDRET_I_KILDE TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    , KILDE_IS VARCHAR2(12 CHAR) DEFAULT ' ' NOT NULL
    , REGION CHAR(1 CHAR) DEFAULT ' ' NOT NULL
    , ID_PS_LOP NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 200 NOT NULL
    , OPPDATERT TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    );

CREATE TABLE #SKJEMA#.PS_VEDTAK_20
( PS01_PERSONKEY NUMBER(15, 0) NOT NULL
    , PS20_FTRYGD_FOM NUMBER(6, 0) NOT NULL
    , PS20_INNTEKT NUMBER(7, 0) NOT NULL
    , PS20_INNT_KODE2 CHAR(1 CHAR) NOT NULL
    , PS20_ART_RTV CHAR(1 CHAR) NOT NULL
    , PS20_BIART CHAR(1 CHAR) NOT NULL
    , PS20_DIVART CHAR(2 CHAR) NOT NULL
    , PS20_INST CHAR(1 CHAR) NOT NULL
    , PS20_GRAD NUMBER(3, 0) NOT NULL
    , PS20_BTILS CHAR(1 CHAR) NOT NULL
    , PS20_BTILSBEL NUMBER(7, 0) NOT NULL
    , PS20_ANTB NUMBER(3, 0) NOT NULL
    , PS20_ANTFB NUMBER(3, 0) NOT NULL
    , PS20_HJS CHAR(2 CHAR) NOT NULL
    , PS20_GRS CHAR(2 CHAR) NOT NULL
    , PS20_ETILL CHAR(1 CHAR) NOT NULL
    , PS20_EKT_4G CHAR(1 CHAR) NOT NULL
    , PS20_ANTKAND NUMBER(3, 0) NOT NULL
    , PS20_EKTEPAR_P CHAR(1 CHAR) NOT NULL
    , PS20_ATTF_GRAD VARCHAR2(3 CHAR) NOT NULL
    , PS20_INSTTREKK NUMBER(6, 0) NOT NULL
    , PS20_UTL_REGLER CHAR(1 CHAR) NOT NULL
    , PS20_EGEN_INNTEKT NUMBER(7, 0) NOT NULL
    , PS20_EKTEF_INNTEKT NUMBER(7, 0) NOT NULL
    , PS20_GARANTISUM_EKTEF NUMBER(6, 0) NOT NULL
    , PS20_REDUKSJON_EKTEF NUMBER(6, 0) NOT NULL
    , PS20_ETILL_0491 CHAR(1 CHAR) NOT NULL
    , PS20_GAVEPENSJON NUMBER(6, 0) NOT NULL
    , PS20_INNT_GR_U_FRIINNT NUMBER(7, 0) NOT NULL
    , PS20_INNT_GR_KODE CHAR(1 CHAR) NOT NULL
    , PS20_GAR_GRAD NUMBER(3, 0) NOT NULL
    , PS20_FRYS_KODE CHAR(1 CHAR) NOT NULL
    , PS20_FRYS_DATO NUMBER(6, 0) NOT NULL
    , PS20_OVERG_STON CHAR(1 CHAR) NOT NULL
    , PS20_SAMORDN NUMBER(6, 0) NOT NULL
    , PS20_INNTGR_FOM NUMBER(6, 0) NOT NULL
    , PS20_UTD_STON CHAR(1 CHAR) NOT NULL
    , PS20_FRADR_HJST NUMBER(4, 0) NOT NULL
    , PS20_VALUTAKODE NUMBER(4, 0) NOT NULL
    , PS20_PENSJ_INNTEKT NUMBER(6, 0) NOT NULL
    , PS20_RTV_PENSJ NUMBER(6, 0) NOT NULL
    , PS20_EKTEF_PENSJ_INNTEKT NUMBER(6, 0) NOT NULL
    , PS20_EKTEF_RTV_PENSJ NUMBER(6, 0) NOT NULL
    , PS20_GT_SKAL_BEREGNES CHAR(1 CHAR) NOT NULL
    , PS20_GARANTISUM_BARN NUMBER(6, 0) NOT NULL
    , PS20_REDUKSJON_BARN NUMBER(6, 0) NOT NULL
    , PS20_LEVER_ATSKILT CHAR(1 CHAR) NOT NULL
    , PS20_INNT_REG CHAR(1 CHAR) NOT NULL
    , PS20_TEI NUMBER(6, 0) NOT NULL
    , PS20_BER_ALT CHAR(1 CHAR) NOT NULL
    , TK_NR                   VARCHAR2(4 BYTE) NOT NULL
    , F_NR                    VARCHAR2(11 BYTE) NOT NULL
    , OPPRETTET               TIMESTAMP (6) DEFAULT current_timestamp NOT NULL
    , ENDRET_I_KILDE          TIMESTAMP (6) DEFAULT current_timestamp NOT NULL
    , KILDE_IS                VARCHAR2(12 CHAR) DEFAULT ' ' NOT NULL
    , REGION                  CHAR(1 CHAR) DEFAULT ' ' NOT NULL
    , ID_PS_FTRYGD             NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 200  NOORDER  NOCYCLE NOT NULL
                                                                                                                                             , OPPDATERT   TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    );

CREATE TABLE #SKJEMA#.PS_TJENESTEPENSJON_50
( PS01_PERSONKEY NUMBER(15, 0) NOT NULL
    , PS50_TPNR NUMBER(4, 0) NOT NULL
    , PS50_TPFOM NUMBER(6, 0) NOT NULL
    , PS50_TPART CHAR(1 CHAR) NOT NULL
    , PS50_TPTOM NUMBER(6, 0) NOT NULL
    , PS50_TP_INFO CHAR(1 CHAR) NOT NULL
    , PS50_REG_DATO NUMBER(8, 0) NOT NULL
    , PS50_OPPDATERT CHAR(2 CHAR) NOT NULL
    , TK_NR VARCHAR2(4 BYTE) NOT NULL
    , F_NR VARCHAR2(11 BYTE) NOT NULL
    , OPPRETTET TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    , ENDRET_I_KILDE TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    , KILDE_IS VARCHAR2(12 CHAR) DEFAULT ' ' NOT NULL
    , REGION CHAR(1 CHAR) DEFAULT ' ' NOT NULL
    , ID_PS_TJEPEN NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 200 NOT NULL
    , OPPDATERT TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    );

CREATE TABLE #SKJEMA#.PS_BELOP_12
( PS01_PERSONKEY NUMBER(15, 0) NOT NULL
    , PS10_KONTONR NUMBER(4, 0) NOT NULL
    , PS10_BEH_KODE CHAR(1 CHAR) NOT NULL
    , PS12_TYPE CHAR(1 CHAR) NOT NULL
    , PS12_MND NUMBER(6, 0) NOT NULL
    , PS12_BEL NUMBER(7, 0) NOT NULL
    , TK_NR VARCHAR2(4 BYTE) NOT NULL
    , F_NR VARCHAR2(11 BYTE) NOT NULL
    , OPPRETTET TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    , ENDRET_I_KILDE TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    , KILDE_IS VARCHAR2(12 CHAR) DEFAULT ' ' NOT NULL
    , REGION CHAR(1 CHAR) DEFAULT ' ' NOT NULL
    , ID_PS_BELOP NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 200 NOT NULL
    , OPPDATERT TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    );

CREATE TABLE #SKJEMA#.TEP_TEKSTER_03
( TEP_IDENT_3 VARCHAR2(7 BYTE) NOT NULL
    , TEP_03_DEL2 VARCHAR2(26 BYTE)
    , TEP_03_DEL3 VARCHAR2(6 BYTE)
    , OPPRETTET TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    );

CREATE TABLE #SKJEMA#.PS_PERSON_01
( PS01_PERSONKEY NUMBER(15, 0) NOT NULL
    , PS01_NSB CHAR(1 CHAR) NOT NULL
    , PS01_TILGANGS_MND NUMBER(6, 0) NOT NULL
    , PS01_PENS_DODSMND NUMBER(7, 0) NOT NULL
    , PS01_OPPHORS_KODE CHAR(1 CHAR) NOT NULL
    , PS01_SIST_UTB_MND NUMBER(6, 0) NOT NULL
    , PS01_KORTNR_LAV NUMBER(7, 0) NOT NULL
    , PS01_KORT_ANT CHAR(1 CHAR) NOT NULL
    , PS01_OPPHOR_MND NUMBER(6, 0) NOT NULL
    , PS01_PM_MASK CHAR(2 CHAR) NOT NULL
    , PS01_PM1 CHAR(2 CHAR) NOT NULL
    , PS01_PM2 CHAR(2 CHAR) NOT NULL
    , PS01_TRYGDETID NUMBER(2, 0) NOT NULL
    , PS01_ETTERBET NUMBER(6, 0) NOT NULL
    , PS01_TRYGDETID_E NUMBER(2, 0) NOT NULL
    , TK_NR VARCHAR2(4 BYTE) NOT NULL
    , F_NR VARCHAR2(11 BYTE) NOT NULL
    , OPPRETTET TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    , ENDRET_I_KILDE TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    , KILDE_IS VARCHAR2(12 CHAR) DEFAULT ' ' NOT NULL
    , REGION CHAR(1 CHAR) DEFAULT ' ' NOT NULL
    , ID_PS_PERS NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 200 NOT NULL
    , OPPDATERT TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    )
;

CREATE TABLE IMS_REPL_T3.TEP_ORDN
(ORDN_NR VARCHAR2(7 BYTE)  NOT NULL
    ,P_NAVN  VARCHAR2(23 BYTE)
    ,P_ADR1  VARCHAR2(23 BYTE)
    ,P_ADR2  VARCHAR2(21 BYTE)
    ,POSTNR  VARCHAR2(4 BYTE)
    ,OPPRETTET TIMESTAMP(6) DEFAULT current_timestamp NOT NULL
    ,ID_TEP_IDENT_O NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 200 NOT NULL
);