create table replikering_status(
    ID_REP_STATUS NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SCHEMA_NAME VARCHAR(50) NOT NULL,
    TABLE_NAME VARCHAR(50) NOT NULL,
    READY NUMBER(1, 0),
    UNIQUE (SCHEMA_NAME, TABLE_NAME)
);
