name: master

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Bygg og test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Set cache key
        run: |
          echo "CACHE_KEY=$(expr $(date +%V))" >> $GITHUB_ENV
          echo "TIMESTAMP=$(expr $(date +%Y%m%d%H%M%S))" >> $GITHUB_ENV

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ env.CACHE_KEY }}

      - name: Build artifacts
        run: mvn verify

      - name: Bygg og push docker image til GAR
        uses: nais/docker-build-push@0e73849f69ff260ee27597553c0a7848ca4e9795 # v0
        id: docker-build-push
        with:
          team: infotrygd

      - name: Deploy back-end til dev-fss
        uses: nais/deploy/actions/deploy@027a91857992525139798892f2804b0ca21f4af6 # v2
        env:
          CLUSTER: dev-fss
          RESOURCE: nais/app/backend.yaml
          VARS: nais/dev.json
          VAR: image=${{ steps.docker-build-push.outputs.image  }}

      - name: Deploy back-end til prod-fss
        if: github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'ci skip')
        uses: nais/deploy/actions/deploy@027a91857992525139798892f2804b0ca21f4af6 # v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/app/backend.yaml
          VARS: nais/prod.json
          VAR: image=${{ steps.docker-build-push.outputs.image  }}
