name: PR build

on: [pull_request]

jobs:
  build:
    name: Bygg pull-request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'

      - name: Set cache key
        run: |
          echo "CACHE_KEY=$(expr $(date +%V))" >> $GITHUB_ENV
          echo "TIMESTAMP=$(expr $(date +%Y%m%d%H%M%S))" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ env.CACHE_KEY }}

      - name: Build artifacts
        run: mvn verify

      - name: Bygg og push docker image til GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: infotrygd
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # Provided as Organization Secret
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # Provided as Organization Variable
